apiVersion: v1
kind: ConfigMap
metadata:
  name: landing-page-html
  namespace: landing-page
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Labs AI Kubernetes Portal</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap');

        body, html {
          margin: 0;
          padding: 0;
          font-family: 'Inter', sans-serif;
          height: 100%;
          background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);
          color: #f0f0f0;
          overflow-x: hidden;
        }

        #particles-js {
          position: fixed;
          top: 0;
          left: 0;
          width: 100%;
          height: 100%;
          z-index: -1;
        }

        header {
          text-align: center;
          padding: 70px 20px 40px 20px;
        }

        .title-box {
          display: inline-block;
          padding: 35px;
          border-radius: 20px;
          background: rgba(255,255,255,0.05);
          backdrop-filter: blur(10px);
          box-shadow: 0 8px 30px rgba(0,0,0,0.6);
          max-width: 850px;
        }

        header h1 {
          font-size: 3.5em;
          font-weight: 800;
          background: linear-gradient(90deg, #ff00cc, #3333ff, #00f2fe);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          margin-bottom: 15px;
        }

        header p {
          font-size: 1.2em;
          color: #cccccc;
          line-height: 1.7;
        }

        .tech-labels {
          text-align: center;
          margin: 40px 0;
        }

        .tech-labels span {
          display: inline-block;
          padding: 10px 20px;
          margin: 8px;
          border-radius: 25px;
          font-weight: 600;
          font-size: 0.95em;
          background: rgba(255,255,255,0.08);
          border: 1px solid rgba(255,255,255,0.2);
          backdrop-filter: blur(6px);
          transition: all 0.3s ease;
        }

        .tech-labels span:hover {
          transform: scale(1.1);
          background: linear-gradient(90deg, #ff00cc, #3333ff, #00f2fe);
          color: #fff;
        }

        .project-desc {
          max-width: 900px;
          margin: 20px auto;
          padding: 30px;
          border-radius: 18px;
          background: rgba(255,255,255,0.06);
          backdrop-filter: blur(8px);
          box-shadow: 0 4px 20px rgba(0,0,0,0.5);
          font-size: 1.1em;
          line-height: 1.7;
        }

        .links {
          display: flex;
          flex-wrap: wrap;
          justify-content: center;
          margin: 60px 0;
          gap: 25px;
        }

        .card {
          background: rgba(255,255,255,0.06);
          border: 1px solid rgba(255,255,255,0.15);
          backdrop-filter: blur(8px);
          border-radius: 20px;
          width: 220px;
          height: 130px;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          text-decoration: none;
          color: #fff;
          font-size: 1.1em;
          font-weight: 600;
          transition: all 0.3s ease;
        }

        .card:hover {
          transform: translateY(-6px) scale(1.05);
          background: linear-gradient(135deg, #ff00cc, #3333ff, #00f2fe);
          color: #fff;
          box-shadow: 0 10px 25px rgba(0,0,0,0.6);
        }

        .card span {
          font-size: 1.8em;
          margin-bottom: 10px;
        }

        footer {
          text-align: center;
          padding: 30px;
          font-size: 0.9em;
          color: #aaaaaa;
          border-top: 1px solid rgba(255,255,255,0.1);
        }
      </style>
    </head>
    <body>
      <div id="particles-js"></div>

      <header>
        <div class="title-box">
          <h1>Labs AI Kubernetes Portal</h1>
          <p>Experience a next-gen AI-driven cloud lab. From Kubernetes deployments to GitOps automation, monitoring, and observability — everything runs seamlessly on AWS EKS.</p>
        </div>
      </header>

      <div class="tech-labels">
        <span>AI</span>
        <span>AWS</span>
        <span>EKS</span>
        <span>Kubernetes</span>
        <span>Terraform</span>
        <span>GitHub Actions</span>
        <span>ArgoCD</span>
        <span>Grafana</span>
        <span>Prometheus</span>
      </div>

      <div class="project-desc">
        <p>This environment demonstrates a secure and automated AI-centric cloud platform built with Infrastructure as Code and GitOps. Using Terraform and GitHub Actions, infrastructure is provisioned and updated continuously. ArgoCD powers seamless GitOps-based deployments, while observability is achieved with Grafana and Prometheus.</p>
        <p>All services are accessible from this unified landing page, designed for professionals exploring AI workflows, automation, and modern DevOps practices.</p>
      </div>

      <div class="links">
        <a href="https://2048.labs.vettlyai.com" class="card"><span>🎮</span>Play 2048</a>
        <a href="https://grafana.labs.vettlyai.com" class="card"><span>📊</span>Grafana</a>
        <a href="https://prometheus.labs.vettlyai.com" class="card"><span>📈</span>Prometheus</a>
        <a href="https://argocd.labs.vettlyai.com" class="card"><span>🚀</span>ArgoCD</a>
      </div>

      <footer>
        &copy; 2025 Labs AI Cloud | Built on AWS EKS with GitOps Automation
      </footer>

      <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
      <script>
        particlesJS("particles-js", {
          "particles": {
            "number": { "value": 120, "density": { "enable": true, "value_area": 800 } },
            "color": { "value": ["#ff00cc", "#3333ff", "#00f2fe"] },
            "shape": { "type": "circle" },
            "opacity": { "value": 0.6 },
            "size": { "value": 2 },
            "line_linked": { "enable": true, "distance": 130, "color": "#888", "opacity": 0.4, "width": 1 },
            "move": { "enable": true, "speed": 2.5 }
          },
          "interactivity": {
            "events": { "onhover": { "enable": true, "mode": "grab" }, "onclick": { "enable": true, "mode": "push" } },
            "modes": { "grab": { "distance": 150, "line_linked": { "opacity": 0.7 } }, "push": { "particles_nb": 5 } }
          },
          "retina_detect": true
        });
      </script>
    </body>
    </html>
