apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec: 
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: ka.sharif01@gmail.com
    privateKeySecretRef:
      name: wildcard-issuer-key
    solvers:
      - dns01:
          route53:
            hostedZoneID: Z02400013U7K3OO6ZCCK8  
            region: eu-west-2
