apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/ks-ahmed/eks-secure-gitops-deploy
    targetRevision: HEAD
    path: kubernetes/game-2048  # <- app folder only
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
