apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-2048
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/ks-ahmed/eks-secure-gitops-deploy
    targetRevision: HEAD
    path: kubernetes/2048.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/ks-ahmed/eks-secure-gitops-deploy
    targetRevision: HEAD
    path: kubernetes/grafana-prom.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-ingress
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/ks-ahmed/eks-secure-gitops-deploy
    targetRevision: HEAD
    path: kubernetes/shared-ingress.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
