apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing-page
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/ks-ahmed/eks-secure-gitops-deploy
    targetRevision: HEAD
    path: kubernetes/landing-page
  destination:
    server: https://kubernetes.default.svc
    namespace: landing-page
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
