apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  namespace: default
  labels:
    app: game-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      securityContext:
        runAsUser: 1000  # Non-root user ID
        runAsGroup: 1000 # Non-root group ID
        fsGroup: 1000    # Group ID for file system
      containers:
        - name: game-2048
          image: 957045488159.dkr.ecr.eu-west-2.amazonaws.com/eksapp:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ecr-secret
