apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  namespace: default
  labels:
    app: game-2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
        - name: game-2048
          image: eksapp
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ecr-secret


---
apiVersion: v1
kind: Service
metadata:
  name: game-2048
  namespace: default
spec:
  selector:
    app: game-2048
  ports:
    - port: 80          # what Ingress sees
      targetPort: 3000  # what container listens on
  type: ClusterIP
