provider: aws

env:
  - name: AWS_DEFAULT_REGION
    value: eu-west-2

serviceAccount:
  create: false
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::528757784671:role/external-dns

domainFilters:
  - k8s.vettlyai.com

rbac:
  create: true

logLevel: info

sources:
  - service
  - ingress

policy: sync
registry: txt
txtOwnerId: external-dns

extraArgs:
  - --aws-zone-type=public
  - --interval=30s
