provider: aws

env:
  - name: AWS_DEFAULT_REGION
    value: eu-west-2

serviceAccount:
  create: false
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::528757784671:role/external-dns

domainFilters:
  - k8s.yacquub.com

rbac:
  create: true

logLevel: info

sources:
  - service
  - ingress

policy: sync
registry: txt
txtOwnerId: external-dns

interval: 30s

extraArgs:
  - --provider=aws
  - --aws-zone-type=public
  - --registry=txt
  - --txt-owner-id=external-dns
