apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: cert-manager
spec:
  secretName: wildcard-tls
  dnsNames:
    - "*.labs.vettlyai.com"
    - "labs.vettlyai.com"
  issuerRef:
    name: issuer
    kind: ClusterIssuer
