name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check confirmation input
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "yes" ]; then
            echo "Deployment cancelled."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set image tag to commit SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/eks-project:${IMAGE_TAG}
          docker build -t $ECR_URI ./apps

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com

      - name: Scan Docker image with Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/eks-project:${IMAGE_TAG}
          trivy image --severity HIGH,CRITICAL $ECR_URI

      - name: Push Docker image
        run: |
          docker push $ECR_URI
          
      - name: Print Docker image tag
        run: |
          echo "===================================="
          echo "Docker image built and pushed:"
          echo "$ECR_URI"
          echo "Use this IMAGE_TAG in your deploy pipeline:"
          echo "${IMAGE_TAG}"
          echo "===================================="