name: Docker -> ECR

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm image build and push'
        required: true
        default: 'no'

env:
  AWS_REGION: eu-west-2
  IMAGE_TAG: ${{ github.sha }}
  ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-west-2.amazonaws.com/eksapp

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check confirmation input
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "yes" ]; then
            echo "Image build and push cancelled."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:$IMAGE_TAG ./app

      - name: Scan Docker image with Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy image --severity HIGH,CRITICAL $ECR_REPO:$IMAGE_TAG

      - name: Push Docker image
        run: |
          docker push $ECR_REPO:$IMAGE_TAG

      - name: Print Docker image tag
        run: |
          echo "===================================="
          echo "Docker image built and pushed:"
          echo "$ECR_REPO:$IMAGE_TAG"
          echo "Use this IMAGE_TAG in your deploy pipeline:"
          echo "$IMAGE_TAG"
          echo "===================================="
