name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no'
      image_tag:
        description: 'Docker image tag (short commit SHA) to deploy'
        required: true

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check confirmation input
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "yes" ]; then
            echo "Deployment cancelled."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set IMAGE_TAG from input
        run: echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: TFLint Check
        working-directory: terraform
        run: tflint

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: terraform
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: terraform apply -var="image_tag=${IMAGE_TAG}" --auto-approve
