name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm apply'
        required: true
        default: 'no'

env:
  AWS_REGION: eu-west-2

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Check confirmation
        run: |
          if [ "${{ github.event.inputs.confirmation }}" != "yes" ]; then
            echo "Apply cancelled by user."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan 
