name: Terraform Plan

on:
  workflow_dispatch:  # No inputs needed now

env:
  AWS_REGION: eu-west-2

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.50.3

      - name: Terraform Init 
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: TFLint Check
        working-directory: terraform
        run: tflint

      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan -out=tfplan

      - name: Upload tfplan (binary)
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan
